In [2]:
import numpy as np

In [3]:
a = np.asarray([[1,2,3,4], [5,6,7,8]])
def mod_arr(a):
    a[0,0] = 100
    return a

print(a)

print(mod_arr(a))

print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[100   2   3   4]
 [  5   6   7   8]]
[[100   2   3   4]
 [  5   6   7   8]]


In [4]:
a = np.asarray([[1,2,3,4], [5,6,7,8]])

def mod_arr(a):
    x = a
    x[0,0] = 100
    return x

print(a)

print(mod_arr(a))

print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[100   2   3   4]
 [  5   6   7   8]]
[[100   2   3   4]
 [  5   6   7   8]]


In [8]:
import pandas as pd

In [24]:
df=pd.DataFrame({'banana':[1,2,3,4], 'bean':[5,6,7,8]})
x = df['banana'] #  this is not assigned by value, but by reference!!!!
df

banana  bean
0       1     5
1       2     6
2       3     7
3       4     8

In [25]:
x

0    1
1    2
2    3
3    4
Name: banana, dtype: int64

In [26]:
x[3] = 10
x

0     1
1     2
2     3
3    10
Name: banana, dtype: int64

In [27]:
df

banana  bean
0       1     5
1       2     6
2       3     7
3      10     8

In [ ]:
# so it changes the dataframe!!!

In [ ]:
# This doesn't happen to immuntable types, like strings:

In [31]:
a = 'babbelbubbel'

def mod_arr(x):
    #x = a
    x = 'Z'+x
    return x

print(a)

print(mod_arr(a))

print(a)

babbelbubbel
Zbabbelbubbel
babbelbubbel
